### ISSUE TITLE
Add setFullDate(), setDay(), setMonth() etc.

### ISSUE THREAD

**Issue by Madskunk** [mikecoj/MCDatepicker#10]
Would it be possible for you to add a simple `setFullDate()` method which takes a `Date` object and sets the value of the input using the current date format?  I'd like to be able to set the date from elsewhere in my project, but not have to worry about the date format, I simply give you the date and you format it.

Also, as you have `getDate()`, `getDay()`, etc. methods, similar `setDay()`, `setMonth()`, etc. methods would be appreciated, allowing me to move the user selected date on a month, or forward a day, etc.

**Comment by mikecoj** [comment]
Hey,

sure, i can add these methods!

**Comment by mikecoj** [comment]
Hi there,
The methods you've requested were added in the new version, please check them out!
Thank you!
