### ISSUE TITLE
Can this be made to always show with the inline viewer on mobile, with an override option to always show modal?

### ISSUE THREAD

**Issue by ashenshugarRET** [mikecoj/MCDatepicker#12]
Is it possible to have the datepicker always open with the inline mode if on a mobile browser, even if set as modal in the options? The modal option doesn't work well with browsers on my phone for instance. Perhaps an option to over-ride inlin on mobile could also be include if is necessary to show the modal version all the time.

**Comment by mikecoj** [comment]
I will try to optimise the animations on mobile or switch them off, i think this will help.

**Comment by ashenshugarRET** [comment]
For my purposes the latest development commit fixes the issue
