### ISSUE TITLE
selectedDate adds +1 to month

### ISSUE THREAD

**Issue by ArashYounesi** [mikecoj/MCDatepicker#13]
`selectedDate: new Date(2021,0, 22)`

top code will select `january` !!

**Comment by mikecoj** [comment]
That's correct, `new Date(2021,0, 22)` is equal to: `Fri Jan 22 2021...`

**Comment by ArashYounesi** [comment]
Thanks @mikecoj 
I did not know this was a JavaScript flaws not your library
Thanks for your amazing library
