### ISSUE TITLE
(Request) Specific Click Handling

### ISSUE THREAD

**Issue by stkol76** [mikecoj/MCDatepicker#17]
Hi Mike,

After last time I have emplemented the amazing MCDatepicker to another page where I use some jQuery button click events to hide/show/toggle text and DIV´s, but when I use the MCDatepicker and click any element in it it toggles my DIV´s and, and I was wondering if it was possible that the MCDatepicker somehow could be coded so that it would only target what it should, meaning the specific datepicker input, so to avoid that it will interact with other elements in a page? .. i.e  if you have 2 datepickers or more with different ids, so that the click handling could be set to only target the specific element and not anything else whether it is DIV´s, Buttons .. I hope this gives meaning, else I will be happy to explain further :-)

**Comment by louis123562** [comment]
I think that your selectors in your jQuery event-listeners are wrong - can you show us some of them or an example, where the problem occurs?

Thank you :)

**Comment by mikecoj** [comment]
Hey @stkol76,
i think would be better if you could show us some code!

@louis123562 , thanks for your help, appreciate that!

**Comment by louis123562** [comment]
@mikecoj i really like to help; this datepicker is super nice :)

**Comment by stkol76** [comment]
Hi @mikecoj  & @louis123562 .. you are so right, I am so sorry to have bothered you both with this, 

when you @louis123562 first wrote back I began to "minify" the 6000+ line code (yes, its a very large and complex page I work on) so that it would be easier to present to you, but in the process I fell over some jQuery that did not make much sense, since they did not target its parrent but did it globally instead, when I sorted that out everything suddently worked like a charm, so it was simply a matter of me stairing blind on my code  ;-( THANKS!

.. and @louis123562  I could not agree more, its a super cool and nice work you have made @mikecoj  ;-)

**Comment by louis123562** [comment]
Hey :)

No problem - can you close this issue?
