### ISSUE TITLE
[Feature Request] Adding custom headline/text to MCDatepicker

### ISSUE THREAD

**Issue by stkol76** [mikecoj/MCDatepicker#18]
Hi @mikecoj  :-)

I am using MCDatepicker on a page where I have a StartDate selector and a EndDate selector (2 different input fields) for each users listed on that page, and since I have multiple listet users on the page and two different date types it would be more userfriendly if I could add a headline to the MCDatepicker Modal so that the user operating the page could see which type and which user they are changing dates on .. would it somehow be possible to have that feature and? :-)

**Some screensshot to illustrate:**

_(Red Arrows and boxes to illustrate suggestions for placement of the custom headline/text)_

![image](https://user-images.githubusercontent.com/1684599/117533183-bb54bc00-afeb-11eb-9056-ae9c6650b694.png)

Best Regards
Stig :-)

**Comment by mikecoj** [comment]
Hi there,

I think this should be handled by the application, not by the MCDatepicker.

In your specific case, you can change the border color of the input element when the user clicks on that input. 
And in the case of the user, after the calendar closes, you still need to know for which one is that selected date.

Thank you!
