### ISSUE TITLE
different date output format

### ISSUE THREAD

**Issue by louis123562** [mikecoj/MCDatepicker#2]
hey, i like your datepicker much.

Is it possible to accept date formats like 'DD.MM.YYYY' / 'DD.MMM.YYYY'?

I would like to use your datepicker on a german website, but all i can get is 'DD-MM-YYYY'.

Thanks in advance, Louis

#edit

^(?:(d{1,4}|m{1,4}|y{4}|y{2})?\b(?:(?:,\s)|[-.\s\/]{1})?(d{1,4}|m{1,4}|y{4}|y{2})?\b(?:(?:,\s)|[.-\s\/]{1})?(d{1,4}|m{1,4}|y{4}|y{2})\b(?:(?:,\s)|[.-\s\/]{1})?(d{1,4}|m{1,4}|y{2}|y{4})?\b)$

this should be the correct Regex for it, allows both - and .

**Comment by mikecoj** [comment]
Hey @louis123562, the regex was updated.
Thank you!

**Comment by louis123562** [comment]
Thank you, we really enjoy this picker!!
