### ISSUE TITLE
Is it possible to programmatically change the dateFormat of a datepicker instance

### ISSUE THREAD

**Issue by ashenshugarRET** [mikecoj/MCDatepicker#20]
Hello,

I would like to be able to implement a panel of buttons which change the date format of a particular datepicker instance if a button is pressed.

Is it possible to change the dateFormat property of a created datepicker instance with javascript from elsewhere on a page?

Thanks

**Comment by ashenshugarRET** [comment]
I managed to get this to work using the solution to issue #15 as a starting point.
A JSFiddle of a working example is here: [https://jsfiddle.net/ashenshugar/ofqg2yax/](https://jsfiddle.net/ashenshugar/ofqg2yax/)

**Comment by mikecoj** [comment]
Hi there,
Thanks for sharing with us your solution!

**Comment by ashenshugarRET** [comment]
No problem, hope it is useful for someone, I've updated it to use your improved input box and icon solution for this issue https://github.com/mikecoj/MCDatepicker/issues/22#issuecomment-841618464
