### ISSUE TITLE
min(), max() and clamp() dont work on Edge for Mobile

### ISSUE THREAD

**Issue by Remling97** [mikecoj/MCDatepicker#21]
I'm using Edge on Android most of the times and i just noticed that min(), max() and clamp() dont work there, so the datepicker looks like this

![185222461_901011457406783_8697049853151268521_n](https://user-images.githubusercontent.com/57572162/118091157-cb451500-b3ca-11eb-8b10-438abe35802e.jpg)

**Comment by mikecoj** [comment]
Hi there, 

Will add a polyfill for this.

Thank you!

**Comment by mikecoj** [comment]
Hi there,
This issue is fixed in the new version!
