### ISSUE TITLE
change sequence of weekdays

### ISSUE THREAD

**Issue by louis123562** [mikecoj/MCDatepicker#3]
hey, is it possible to change the sequence of the weekdays?
we start with monday in germany.

**Comment by mikecoj** [comment]
Hey!
It doesn't have this kind of functionality right now, but I will definitely add it.

**Comment by louis123562** [comment]
Would be great :)

**Comment by mikecoj** [comment]
hey @louis123562 ,  now you can change the sequence of the weekdays by adding the property `firstWeekday` to the options, see the example below:

```
const datepicker = MCDatepicker.create({
	el: '#datepicker',
	firstWeekday: 1
});
```

**Comment by louis123562** [comment]
hey @mikecoj,

thank you very much for this feature!!
