### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by stkol76** [mikecoj/MCDatepicker#30]
Hi Mike,

I have the MCDatepicker running on several pages in my project, but I am expirience  some issues with it on a specific page (all other works) but I have spent 2 days debugging what script it is that is breaking the MCDatepicker on that specific page and to be frank I cannot find it, so I hope you would be able to point me in the right direction. (I am using the CDN so I am runnig the latest version)

The Error I get is :

```
mc-calendar.min.js:1 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLInputElement'
    |     property 'jQuery351066511655056161862' -> object with constructor 'Object'
    |     property 'Parsley' -> object with constructor 'Field'
    --- property 'element' closes the circle
    at JSON.stringify (<anonymous>)
    at VM30899 mc-calendar.min.js:1
    at Array.find (<anonymous>)
    at Object.open (VM30899 mc-calendar.min.js:1)
    at Object.open (VM30899 mc-calendar.min.js:1)
    at HTMLInputElement.U.e.linkedElement.e.linkedElement.onfocus (VM30899 mc-calendar.min.js:1) 
```

I am quite certain that another script is causing this, but as I wrote before I have not been able to figure out why and which it is .. Can you help? :-)

**Comment by louis123562** [comment]
What jQuery version + minified/minimal are you running?

**Comment by stkol76** [comment]
Hi Louis,

I am using https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js

**Comment by stkol76** [comment]
Just testet with 3.6.0 non-minified, and still the same issue (https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.js)

**Comment by louis123562** [comment]
I made a uncompressed version of the datepicker.js, can you try it with this? So we can get the real line in source which makes the trouble.
[mc-calendar.min.js.zip](https://github.com/mikecoj/MCDatepicker/files/6602842/mc-calendar.min.js.zip)

**Comment by stkol76** [comment]
This is the error output now:

`mc-calendar.js:29 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLInputElement'
    |     property 'jQuery360024701552671865182' -> object with constructor 'Object'
    |     property 'Parsley' -> object with constructor 'Field'
    --- property 'element' closes the circle
    at JSON.stringify (<anonymous>)
    at eval (mc-calendar.js:29)
    at Array.find (<anonymous>)
    at Object.open (mc-calendar.js:28)
    at Object.open (instance.js:47)
    at HTMLInputElement.instance.linkedElement.onfocus (listeners.js:394)`

**Comment by louis123562** [comment]
Ah - i didnt check the file i gave you. I am not so good with webpack, i dont know how i can make a regular js-file - not this mushed up.

At least we know now, that it comes from the checker.js ?!

I guess @mikecoj can provide you a better file for testing.

**Comment by stkol76** [comment]
Thank you Louis so far, that was a great effort, :-)

I will await the ju´dgement from @mikecoj with crossed fingers ;-)

**Comment by mikecoj** [comment]
Hey guys! 
Thanks for this issue !! 
@stkol76, could you please reproduce this in [jsfiddle](https://jsfiddle.net/) and share the link with us?, will be easier for me to debug it.

**Comment by stkol76** [comment]
@mikecoj I will get onto it right away :-)

**Comment by mikecoj** [comment]
Great,
Thank you!

**Comment by stkol76** [comment]
Even better .. I have found what causes the issue while stripping the page appart for JSFiddle:

```
<script class="SendNewExternalEmployeeForm">
  $(function () {
  $('#SendNewExternalEmployeeForm').parsley().on('field:validated', function() {
  var ok = $('.parsley-error').length === 0;
  $('.bs-callout-info').toggleClass('hidden', !ok);
  $('.bs-callout-warning').toggleClass('hidden', ok);
  })
  .on('form:submit', function() {
  return true; 
  });
  });
</script>
```

**Comment by stkol76** [comment]
Okay .. hmm .. Now I tried removing the above script from the large page I am working on, but that does not help, but doing it in this fiddle does : https://jsfiddle.net/skolbaek/o7m9680j/9/ as you can try

**Comment by stkol76** [comment]
@mikecoj Can I email you a link to test page with the entire plain code? .. I do not want to post it here.

**Comment by mikecoj** [comment]
Yes, of course!

**Comment by stkol76** [comment]
I have just sent e-mail to mihai040493@gmail.com :-)

**Comment by mikecoj** [comment]
Hey, 
I've just looked into the page you sent me, and I've found the issue.
This is an MCDatepicker issue. 
I'm fixing this now!
Thank you!!

**Comment by stkol76** [comment]
THANK YOU @mikecoj , I really appriciate that, this means alot for my further development :-) .. look forward to receive news ;-)

**Comment by mikecoj** [comment]
Just pushed a new patch version, try it out!

**Comment by stkol76** [comment]
Absolutely brilliant!!!! Works lperfectly @mikecoj ! .. Thank you so much :-)

**Comment by mikecoj** [comment]
Thanks for finding this issue! This is a great contribution to the project! :))
