### ISSUE TITLE
mc-table__body seems to fill only half of the screen on Chromium based browsers on mobile

### ISSUE THREAD

**Issue by bariccattion** [mikecoj/MCDatepicker#33]
Before I describe the issue, I just wanted to say, thanks for the best Datepicker library that exists!
When using your library on Chromium based browsers, on a mobile view, with the modal bodyType, the mc-table__body seems to fill only half of the space available.
![WhatsApp Image 2021-06-23 at 17 44 05](https://user-images.githubusercontent.com/19714408/123167878-04da5880-d42c-11eb-8fb2-2fb8218a6f95.jpeg)

The issue only seems to exist on Chromium based browsers, when using Firefox, it works as expected.

**Comment by louis123562** [comment]
I made the screenshot on Chrome.
 Did you try in an empty project @chardin1 ?
![Screenshot_20210624-013150_Chrome](https://user-images.githubusercontent.com/36068395/123180758-35ea7580-d48c-11eb-887d-07653a68214d.jpg)

**Comment by bariccattion** [comment]
Setting 
```
.mc-calendar {
  line-height: 3 !important;
}
```
seems to fix the issue, spent the entire day trying to figure it out why it was like that, if I had anything messing it up, but I'm still not sure what caused it... Thanks for the great library guys

**Comment by mikecoj** [comment]
Hi there, 
It works on all browsers, except IE, so in your case, you probably changed the CSS `flex` property of the `mc-table__body` class, or you are using a CSS library.
Will be nice if you could reproduce it and share a link with us so we could debug it

**Comment by bariccattion** [comment]
Will try to reproduce as soon as I can, my project is on a tight deadline, as soon as I finish it (in the next few weeks) I'll try to reproduce and will come back to see what is going on

**Comment by bariccattion** [comment]
Apparently it was a problem with a Datatable theme changing the font-size of all table...
