### ISSUE TITLE
Custom days error

### ISSUE THREAD

**Issue by markovicpetar788** [mikecoj/MCDatepicker#39]
Hi, it's giving me issue :
![image](https://user-images.githubusercontent.com/78183509/125644659-0e838aed-19e0-4040-9576-ad10a29f9e42.png)
although I don't change allowedYears but I changed name of days.

How to fix this?

**Comment by mikecoj** [comment]
Hi there, 
can you please send the configurations of the calendar?

**Comment by markovicpetar788** [comment]
const myDatePicker = MCDatepicker.create({ 
  el: '#kalendar',
  bodyType: 'inline',
  dateFormat: 'DD-MM-YYYY',
  customWeekDays: ['P', 'U', 'S', 'C', 'P', 'S', 'N'],
  customMonths: [
    'Januar',
    'Februar',
    'Mart',
    'April',
    'Maj',
    'Jun',
    'Jul',
    'Avgust',
    'Septembar',
    'Oktobar',
    'Novembar',
    'Decembar',
  ], 
disableWeekends: false,
customOkBTN: 'Izaberi',
customClearBTN: 'Obriši',
customCancelBTN: 'Zatvori',
  });

This?

**Comment by ashenshugarRET** [comment]
Try deleting the comma after 'Decembar'

**Comment by mikecoj** [comment]
You just need to add the entire name of the weekday.

This option is used on date formatting too, and it needs the full weekday name to do this properly.

**Comment by markovicpetar788** [comment]
I put two letters and it works.
