### ISSUE TITLE
Is it possible to specify min and max dates

### ISSUE THREAD

**Issue by ashenshugarRET** [mikecoj/MCDatepicker#4]
I'd like to be able to define the range of selectable dates, is it possible to set min and max selectable dates?

**Comment by mikecoj** [comment]
Hey @ashenshugarRET , it's not possible at this point, but i will add this option very soon! 
Thank you!!

**Comment by mikecoj** [comment]
Hey @ashenshugarRET, just added minDate and maxDate config options!

**Comment by ashenshugarRET** [comment]
Hello @mikecoj Thanks for implementing this. There seems to be a bug, when I define a minDate and maxDate on opening the dialog it is not possible to change Year (see attached picture) using the year selector arrows, if you use the month selector arrows to navigate to the previous year it is then possible to navigate with the year arrows, but not to the year of the maxDate (ie if max date is 22-03-2020 it is not possible to navigate back up to 2020
![year not selectable with maxDate used](https://user-images.githubusercontent.com/42817877/112203201-2f88fb00-8c0a-11eb-945c-e66e3edd9952.PNG)

**Comment by mikecoj** [comment]
Could you please send me the minDate and maxDate options so i could debug it?

**Comment by ashenshugarRET** [comment]
Sure here is the code I am using:
```
<script>
            const myDatePickerDay = MCDatepicker.create({ 
                el: '#Selected_Day',
                dateFormat: 'DD-MM-YYYY',
                minDate: new Date("2015-09-25"),
                maxDate: new Date("2020-03-22"),
                selectedDate: new Date("2020-03-22")
            })
</script>
```

**Comment by mikecoj** [comment]
Hey @ashenshugarRET it should be fixed in the latest version

**Comment by ashenshugarRET** [comment]
Hello,

It's better but not perfect yet...
Here is my code:
```
<script>
            const myDatePickerday = MCDatepicker.create({ 
                el: '#Selected_Enphase_Day',
                bodyType: 'modal',
                showCalendarDisplay: true,
                disableWeekends: false,
                dateFormat: 'DD-MM-YYYY',
                firstWeekday: 1,
                minDate: new Date(2015,09,25),
                maxDate: new Date(2021,03,23),
                selectedDate: new Date(Date.now() - (24*60*60*1000))
            })
</script>
```
However the minimum date I can select is 25 October 2015 and not 25 September 2015 and th emaximum date I can select is 23 April 2021 and not 23 March 2021
![image](https://user-images.githubusercontent.com/42817877/112297633-07db7680-8c8e-11eb-97ee-ddcf57fa4a37.png)
![image](https://user-images.githubusercontent.com/42817877/112298829-1d9d6b80-8c8f-11eb-9763-900293a25d7c.png)

If I change the format of the minDate to `minDate: new Date("2015-09-25"),` and maxDate to `maxDate: new Date("2021-03-23"),` then it works as expected...
![image](https://user-images.githubusercontent.com/42817877/112298017-7587a280-8c8e-11eb-833f-6a6c66a3cd12.png)
![image](https://user-images.githubusercontent.com/42817877/112299058-55a4ae80-8c8f-11eb-9133-de82fe0f3b4e.png)

If I am on a month before September, August for example, and use the year arrows to navigate I am unable to select 2015, I assume this is because because August 2015 is out of the min - max range, could it be made to show September 2015 in this instance. This is the same for navigating up and being on a move after the max date month.
![image](https://user-images.githubusercontent.com/42817877/112299980-42461300-8c90-11eb-9ec6-9c98ed961d7d.png)
![image](https://user-images.githubusercontent.com/42817877/112300043-59850080-8c90-11eb-8b4c-4a74bbcd8c00.png)

Thanks for all your work in creating this.

**Comment by mikecoj** [comment]
You are getting this result because you're using individual date components ( year, monthIndex, day ) to create the date instance. According to MDN docs, the month index begins with 0 for January. So in your case, it should be: `minDate: new Date(2015, 8, 25)` to set the min selectable date to 25th of September 2015.

About the second part..., it's a good idea, thanks!!
I will add this logic!

**Comment by ashenshugarRET** [comment]
Thanks for clarifying the expected format for the month numbering.

**Comment by mikecoj** [comment]
Hey @ashenshugarRET, just added a new version that includes the feature you've requested, also i've added a config option for that so it can be switched off if you want. By default it's on.

**Comment by ashenshugarRET** [comment]
Thanks, that's perfect.
