### ISSUE TITLE
error every time setFullDate is called

### ISSUE THREAD

**Issue by ashenshugarRET** [mikecoj/MCDatepicker#42]
Hello,

Every time I call the setFullDate function I get the following console error:

`mc-calendar.min.js:1 Uncaught TypeError: Cannot read property '_id' of null
    at HTMLDivElement.<anonymous> (mc-calendar.min.js:1)
    at x (mc-calendar.min.js:1)
    at Object.setFullDate (mc-calendar.min.js:1)
    at rightArrowClickStart (test_webpage.php:221)
    at HTMLButtonElement.onclick (test_webpage.php:120)`

However, my local code works as expected...

Here is a  [jsfiddle](https://jsfiddle.net/ashenshugar/237nmsd1/) to the code, however the script error seems to stop that working properly, getFullDate is called when the arrow buttons for the start datepicker are pressed

**Comment by mikecoj** [comment]
Hi there,

Thanks for opening this issue, will fix it ASAP

**Comment by ashenshugarRET** [comment]
Thanks for fixing the issue so quickly.
