### ISSUE TITLE
Have you thought about implementing a month and year view

### ISSUE THREAD

**Issue by ashenshugarRET** [mikecoj/MCDatepicker#5]
I have an implementation where I need to be able to select dates only by month and year (ie April 2016), as well as only the year (2016)

Have you considered implementing selector views that allow this?

Thanks

**Comment by mikecoj** [comment]
That will be a great feature, I will definitely add it.
Thank you!!!

**Comment by ashenshugarRET** [comment]
I've seen you've starting submitting commits to the development branch recently, I'd be happy to start testing the month and year picker views. What options should I use to activate them?
Thanks

**Comment by mikecoj** [comment]
Hey, 
it doesn't require any option, but I still need to add a few more things to make it work properly...

**Comment by ashenshugarRET** [comment]
Thanks, OK I'll wait for you to finish. Would it be possible to link the view to the date format? Ideally I'd like to limit the user to only being able to select the month and year when the date format only has month and year (ie mm-yy) and only be able to select the year when the format is yy or yyyy.
Don't worry if you're not planning to implement this as I have an implementation with HTML date, month and list inputs, but would really like to use this as it looks so much better.

**Comment by mikecoj** [comment]
It's quite interesting..., I like it!! 
I will definitely add this feature!!

**Comment by ashenshugarRET** [comment]
I've been following your progress through the development branch, using the code in a test environment and the newly implemented month and year views are excellent. Thanks!!
I have one comment, it appears the showCalendarDisplay option when set to true for the month and year, is this intentional, a bug, or just you haven't implemented it yet? If it isn't planned to be implemented, that's OK, I'll just standard on the view without the calendar.
Once again thank you for these improvements, this will be perfect for my plans

**Comment by mikecoj** [comment]
hey, 
actually i was thinking to hide the display on desktop for month & year views but you are right, will be better to show it, and the `showCalendarDisplay` option will work in this case. Just fixed that!

**Comment by ashenshugarRET** [comment]
Hi,
I've just tested the month and year views in modal mode with showCalendarDisplay set to true and the calendar information is still not showing.

Thanks
