### ISSUE TITLE
Views of months and years not working on Safari

### ISSUE THREAD

**Issue by jacekf1234** [mikecoj/MCDatepicker#56]
In windows browsers all working very well, but on Safari the calendar has some bugs. When click to change month or year the mc-picker__body not change content from days to months or years.
https://www.youtube.com/watch?v=ECe8xoqBXDo&ab_channel=%C5%81ukaszMachejek

**Comment by mikecoj** [comment]
Hey, 
I just tested the component on safari and it works fine!
Follow the link below and let me know if it works for you too!
https://615f0df210de0e00075be5b3--mcdatepicker-dev.netlify.app/

**Comment by mikecoj** [comment]
Hey, 

Check the new patch version, it should fix this issue!
