### ISSUE TITLE
Change from blur listener to click broke form

### ISSUE THREAD

**Issue by rjpedrosa** [mikecoj/MCDatepicker#57]
Hi,

This change broke a form in one of my websites. Checkboxes/radios and submit button stopped working.
You should not `e.preventDefault` document clicks. Or if you do, make sure you let it through after your custom handler, for untreated cases.

https://github.com/mikecoj/MCDatepicker/commit/7199591a36be5f660b65755e77ddc7bcd3efdfbd

**Comment by mikecoj** [comment]
Hi,

Just pushed a new patch, it should be fixed now!

**Comment by rjpedrosa** [comment]
Hi,

Sorry, just noticed my comment was kind of passive/agressive. Didn't mean to.

Many thanks for the fix and for the excellent plugin. 😉

**Comment by mikecoj** [comment]
Hey, 
No worries! 
Thanks for reporting the issue!!
