### ISSUE TITLE
Compare selected date with date today

### ISSUE THREAD

**Issue by stkol76** [mikecoj/MCDatepicker#58]
Hi @mikecoj 

I hope you can help me .. I have tried to compare the date selected in MCDatepicker using the onSelect() event hook and todays date using jQuery, but so far unsuccessfully .. how can I do this?  .. I have also made a post on StackOverflow without any response here : [https://stackoverflow.com/questions/69653851/how-can-i-check-if-selected-date-in-mcdatepicker-is-today%c2%b4s-date](url) 

Hope you can help me :-)

Best Regards
Stig

**Comment by mikecoj** [comment]
Hey @stkol76,

`onSelect()` hook passes a date object as an argument to its callback function, so you can use any method of the date object. 
To compare 2 dates you need to convert them into numbers, you can use the `valueOf()` method for this.
ex: 
```
datepicker.onSelect((date)=>{
    const newDate = new Date()
    if(date.valueOf() < newDate.valueOf()) console.log("The date is in the past!")
})
```
