### ISSUE TITLE
3 issues found

### ISSUE THREAD

**Issue by stkol76** [mikecoj/MCDatepicker#6]
#1: 
I have found that when I set `minDate: new Date(2021, 03, 29)` instead of actually setting the first selectable date to 29th Martch 2021, the first selectable date is 29th April 2021, is this a bug?

#2: 
I am not able to use language specific characters like i.e æ, ø and å in customWeekDays, which gives me an issue becaus Saturday and Sunday is spelled Lørdag and Søndag in Danish.

#3:
I am unable to find the styling attribute in the CSS file that allows me to position the Modal at a specific fixed or absolute position (I.e 50px from the top ), which gives me quite a headache since the modal opens in the middle of the page, and when your page is more than 4 pages long and you open the modal at the top of the page, the modal is out of site and you need to scroll 2 pages down.

Hope you have any idea how to fix these issues :-)

**Comment by stkol76** [comment]
Update to Issue #1 ..

After seeing the "closed issue" section, I saw that January is 0 so I solved it by setting the month -1, and also removing the leading 0, so the result became minDate: `new Date(2021, 2, 30)` and that solved it :-)

Looking forward to here regarding Issues #2 and #3 :-)

**Comment by mikecoj** [comment]
Hey @stkol76 , just added a new version that should fix them!

**Comment by stkol76** [comment]
Hey @mikecoj  .. you are brilliant, it is deffinetly fixed .. and by the way it is a an awsome work you have done with this component, I have searched the web for 14 days after the perfect date picker, and I have definently found it!

I have found another issue (think it is because I use Bootstrap 4) that the month and year are cut .. yesterday I fixed it my self, but I thought you should know:

![image](https://user-images.githubusercontent.com/1684599/112515884-fb8f1080-8d96-11eb-8895-87bc532a9533.png)

Would it by the way be possible to make so you can change the labels for OK, CANCEL and Clear like you can with days and months? .. I have changed it in the JS file for now, but when new updates come it would be easier :-D

**Comment by mikecoj** [comment]
I'm happy to hear you're enjoying it.
Thank you for such a great feedback, i really appreciate it!

**Comment by mikecoj** [comment]
I'll fix the issue ASAP!

**Comment by stkol76** [comment]
I sure am, its a joy emplementing, and on top of the "easy to work with" you have created a fine looking design, those two not often goes hand in hand ;-)

Great, I will sure look forward to that, Thanks :-)

**Comment by mikecoj** [comment]
Hey @stkol76 the issue should be fixed with the new version, also I've added options for custom button labels as requested!

**Comment by stkol76** [comment]
Hi @mikecoj

The issue with cutting of the month, year and day is almost fixed, but month is still being cut, try to look at the 'g' in below screen.

![image](https://user-images.githubusercontent.com/1684599/112729379-13e46400-8f2c-11eb-9cac-35c0684f9ba2.png)

When I apply the `customClearBTN: 'Nulstil',` and `customCancelBTN: 'ANNULLER',` I am not able to click the input field anymore, meaning that MC Datepicker is not opening, but if I do not appy it then it opens up :-)

**Comment by stkol76** [comment]
Sorry, I have gotten it to work with the custom buttons now, only the month cutting at bottom left ;-)

**Comment by mikecoj** [comment]
Should be fixed now!

**Comment by stkol76** [comment]
Sure is, brilliant Mike .. Thank you for the great work you have done with this component, and your swift fixes, I really appriciate that :-)

**Comment by mikecoj** [comment]
Thanks for helping me to find these issues!!!

**Comment by stkol76** [comment]
That was my pleasure :-) .. An idea for future versions .. Not that I need it now  since I have fixed it adding CSS in the pages I use the component in .. if it was possible to change the colors in like changing the labels, that would be a nice and easy feature. ;-)

**Comment by mikecoj** [comment]
It's on my to-do list for future versions!
Thank you!
