### ISSUE TITLE
disableDates update, bodyType fixed?

### ISSUE THREAD

**Issue by ninobang** [mikecoj/MCDatepicker#61]
hej mike, 
first of all thank you! the browser support for date input is such a crazy mess, what makes your MCDatepicker a welcome light at the end of the tunnel.

just a quick question how would i go about updateing the disableDates? i managed to update minDate by updateing the prevLimitDate variable of my MCDatepicker. but i can't figure out how to update disableDates..

and while i am here, have to admit i didn't look into it to much yet, but is there a way of hidding the input element and showing the MCDatepicker fixed on the page?

so long,...

**Comment by mikecoj** [comment]
Hi there, thanks for the appreciation!

Currently the MCDatepicker, has no dedicated method for updating the disabled dates, but you can simply update the `disableDates` option, ex: `datepicker.options.disableDates.push(new Date())`

What about the second part, unfortunately, the component doesn't support a fixed body type yet.

**Comment by ninobang** [comment]
thank you mike for the tip... i think with this i will get it working. :)
