### ISSUE TITLE
get the button by which the calendar was closed

### ISSUE THREAD

**Issue by louis123562** [mikecoj/MCDatepicker#7]
Hey,

sorry for this bad title / my bad english.

In the documentation (really neat!) you mention the webhooks for closing (https://mcdatepicker.netlify.app/docs/event-hooks#onclose).

Those work like a charm. Is it somehow possible to find out, if the modal was closed by clicking on "ok" or "cancel"?

Both datepicker objects carry a date and i cannot see any attribute to differ those.

Thank you :)

**Comment by mikecoj** [comment]
Hey Luis,

`onClose` hook subscribes the provided callback(s) to a custom event that fires every time the calendar hides.

In the case of the ok button, you can use `onSelect` hook. The provided callback(s), runs when the ok button is clicked.

In the case of the cancel button, I will add a separate hook for that!

**Comment by louis123562** [comment]
perfect :)

**Comment by mikecoj** [comment]
A new hook was added in the last version that solves this!

**Comment by louis123562** [comment]
great :)
