### ISSUE TITLE
getting errors when input is not in DOM

### ISSUE THREAD

**Issue by louis123562** [mikecoj/MCDatepicker#8]
Hey,

when i create constant of datepicker and the specified input field (el) is not in the dom tree yet, i get an error.

Is it possible to change this behaviour? We would like to use the datepicker for multiple inputs and buttons.

Or is it even possible to create a constant/picker without specifieng the input element (el)?

Or should i use hidden input fields for this?!

Would be great if you could add some examples and your opinion for this :)

**Comment by mikecoj** [comment]
Hey,

The `el` config option is the only option that is required. The MCDatepicker uses it to find an element in the DOM tree with the specified id and apply a listener to it that makes the calendar appear.

I could actually make it optional, so you could handle the triggers by yourself.

**Comment by louis123562** [comment]
That would be great :)

**Comment by louis123562** [comment]
hey man, i dont want you make trouble, but how's the progress on this an the other issues?

I am for my self not so familiar with js, i know how to use jQuery and thats all :D

**Comment by mikecoj** [comment]
Hey Luis, 

Actually, I've solved both of them some time ago, but i was working on new features and wanted to merge them in one version.

**Comment by louis123562** [comment]
Hey,

very nice to hear. I am very excited for the new version :)

**Comment by mikecoj** [comment]
Hey Luis, 
this issue is fixed in the last version!

**Comment by louis123562** [comment]
nice to hear, will try out soon :)
