### ISSUE TITLE
minDate weird behaviour

### ISSUE THREAD

**Issue by brezho** [mikecoj/MCDatepicker#95]
Hi there,
thanks for providing this very good looking calendar. Appreciated.

While using the code below, the UI allows selecting a date after the 5th Jan 2024, instead of 5 Dec 2023 as instructed.
Am I doing something wrong?
Cheers

```
<input id="calbox" class="w3-input" onenter="() => dt_cal.open();"  type="text">
<script id="cal_1" type="text/javascript">
    var dt_cal = MCDatepicker.create({
        el: '#calbox',
        minDate: new Date(2023, 12, 5)
    });
</script>
```

**Comment by ashenshugarRET** [comment]
This behaviour is due to how JavaScript handles months, January starts as 0, so December is 11. This confused me when I started, just substrat 1 from your month number and all will be well.

https://www.w3schools.com/jsref/jsref_getmonth.asp

**Comment by brezho** [comment]
Definitely shows my lack of JS knowledge...
Cheers mate, appreciated.
